export type LanguageCode =
  | 'en'
  | 'bn'
  | 'hi'
  | 'ja'
  | 'es'
  | 'ar'
  | 'fr'
  | 'de'
  | 'ru'
  | 'zh';

export interface Dictionary {
  welcome_title: string;
  welcome_sub: string;
  welcome_btn: string;
  logo_name: string;
  btc_label: string;
  btc_loading: string;
  btc_error: string;
  utc_clock: string;
  utc_subtitle: string;
  hunt_title: string;
  hunt_sub: string;
  hunt_desc: string;
  hunt_btn: string;
  hunt_status: string;
  hunt_rewards: string;
  hunt_rules_title: string;
  hunt_rule_1: string;
  hunt_rule_2: string;
  hunt_rule_3: string;
  user_title: string;
  user_subtitle: string;
  user_placeholder: string;
  status_lbl: string;
  status_typing: string;
  status_weak: string;
  status_good: string;
  status_premium: string;
  status_invalid: string;
  btn_gen: string;
  btn_copy: string;
  btn_copied: string;
  btn_tg: string;
  credits_by: string;
  mentor_title: string;
  theme_label: string;
  theme_cyber: string;
  theme_crypto: string;
  theme_gaming: string;
  theme_clean: string;
  activity_header: string;
  hunt_tab_info: string;
  hunt_tab_objectives: string;
  hunt_tab_trivia: string;
  hunt_tab_register: string;
  reg_header: string;
  reg_desc: string;
  reg_btn_visit: string;
  reg_step_title: string;
  reg_step_1: string;
  reg_step_2: string;
  reg_step_3: string;
  reg_step_4: string;
  reg_wallet_warning: string;
  swap_title: string;
  swap_subtitle: string;
  swap_connect_wallet: string;
  swap_wallet_modal_title: string;
  swap_wallet_connected: string;
  swap_button_execute: string;
  swap_rate: string;
  swap_gas_fee: string;
  swap_balance: string;
  swap_success_title: string;
  swap_success_desc: string;
  swap_slippage: string;
}
